name: fairmast-data-preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.11
  - zarr<3
  - xarray
  - s3fs
  - matplotlib
  - notebook
  - opencv
  - tqdm
  - ipywidgets
  - scikit-learn
  - black