subset_of_shots:
local: true

task_name: task_2-4

sources_and_signals:
  input_name: &input_keys
    - [magnetics, flux_loop_flux] 
    - [magnetics, b_field_pol_probe_ccbv_field]
    - [magnetics, b_field_pol_probe_obr_field]
    - [magnetics, b_field_pol_probe_obv_field]
    - [magnetics, b_field_tor_probe_saddle_voltage]
    - [pf_active, solenoid_current]
    - [pf_active, coil_current]
    - [pulse_schedule, i_plasma]
    - [summary, power_nbi]
    - [summary, ip]

  actuator_name: &actuator_keys  
    - [pf_active, coil_voltage]
    - [summary, power_nbi]
    - [pulse_schedule, i_plasma]

  output_name: &output_keys
    - [pf_active, solenoid_current]
    - [pf_active, coil_current]
    - [summary, ip]
    - [pulse_schedule, i_plasma]
    - [equilibrium, psi]

standardscaling_setting:
  mean_path: "/../metadata/2025-09-22_stdscaling/flattened_dict_mean_shot.pkl"
  std_path: "/../metadata/2025-09-22_stdscaling/flattened_dict_std_shot.pkl"
  # mean_path: "/../metadata/2025-09-22_stdscaling/dict_mean_shot.pkl"
  # std_path: "/../metadata/2025-09-22_stdscaling/dict_std_shot.pkl"

task_window_segmenter:
  input_keys: *input_keys
  actuator_keys: *actuator_keys
  output_keys: *output_keys
  input_length: 0.005
  output_length: 0.025
  delta: 0 # this is forecasting
  verbose: false

paths:
  data_split_csv_path: ../metadata/2025-05-12/data_splits.csv
