subset_of_shots: 20
local: true
run_evaluation: true

sources_and_signals:
  x_past: &x_past_keys
    - [magnetics, flux_loop_flux] 
    - [pf_active, coil_voltage]
    - [pf_active, coil_current]
    # - [pulse_schedule, i_plasma]
    - [summary, power_nbi]
    # - [pulse_schedule, n_e_line]
    # - ['thomson_scattering', 't_e']
    # - ['thomson_scattering', 'n_e']

  x_future: &x_future_keys
    - [pf_active, coil_voltage]
    - [pf_active, coil_current]
  #   - [summary, power_nbi]

  # y_past: &y_past_keys
  #   - [magnetics, flux_loop_flux] 
  #   - ['thomson_scattering', 't_e']
  #   - [equilibrium, psi]
    # - ['thomson_scattering', 'n_e']

  y_future: &y_future_keys
    - [magnetics, flux_loop_flux] 
    - ['thomson_scattering', 't_e']
    - [equilibrium, psi]

standardscaling_setting:
  mean_path: "/../metadata/2025-09-22_stdscaling/flattened_dict_mean_shot.pkl"
  std_path: "/../metadata/2025-09-22_stdscaling/flattened_dict_std_shot.pkl"
  # mean_path: "/../metadata/2025-09-22_stdscaling/dict_mean_shot.pkl"
  # std_path: "/../metadata/2025-09-22_stdscaling/dict_std_shot.pkl"

rolling_window_segmenter_setting:
  x_past_keys: *x_past_keys
  x_future_keys: *x_future_keys
  # y_past_keys: *y_past_keys
  y_future_keys: *y_future_keys
  verbose: false

paths:
  data_split_csv_path: ../metadata/2025-05-12/data_splits.csv
