subset_of_shots: 128
local: true

cnn_settings:
  D: 64

dataloader_setting:
  # batch_size: 256
  # num_workers: 32
  batch_size: 32
  num_workers: 4
  # batch_size: 8
  # num_workers: 0

training_args:
  lr: 0.00001
  max_epochs: 500
  patience: 5

paths:
  data_output_directory: /output_test/
